<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB; 

class WordsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('words')->insert([
            // 1
            [
                'English' => 'apple',
                'Spanish' => 'manzana',
                'French' => 'pomme',
                'German' => 'Apfel',
                'Japanese' => 'りんご',
                'Serbian' => 'јабука',
                'is_active' => true,
                'category' => 'fruit',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 2
            [
                'English' => 'house',
                'Spanish' => 'casa',
                'French' => 'maison',
                'German' => 'Haus',
                'Japanese' => '家',
                'Serbian' => 'кућа',
                'is_active' => true,
                'category' => 'building',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 3
            [
                'English' => 'car',
                'Spanish' => 'coche',
                'French' => 'voiture',
                'German' => 'Auto',
                'Japanese' => '車',
                'Serbian' => 'аутомобил',
                'is_active' => true,
                'category' => 'vehicle',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 4
            [
                'English' => 'book',
                'Spanish' => 'libro',
                'French' => 'livre',
                'German' => 'Buch',
                'Japanese' => '本',
                'Serbian' => 'књига',
                'is_active' => true,
                'category' => 'object',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 5
            [
                'English' => 'dog',
                'Spanish' => 'perro',
                'French' => 'chien',
                'German' => 'Hund',
                'Japanese' => '犬',
                'Serbian' => 'пас',
                'is_active' => true,
                'category' => 'animal',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 6
            [
                'English' => 'cat',
                'Spanish' => 'gato',
                'French' => 'chat',
                'German' => 'Katze',
                'Japanese' => '猫',
                'Serbian' => 'мачка',
                'is_active' => true,
                'category' => 'animal',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 7
            [
                'English' => 'water',
                'Spanish' => 'agua',
                'French' => 'eau',
                'German' => 'Wasser',
                'Japanese' => '水',
                'Serbian' => 'вода',
                'is_active' => true,
                'category' => 'liquid',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 8
            [
                'English' => 'sun',
                'Spanish' => 'sol',
                'French' => 'soleil',
                'German' => 'Sonne',
                'Japanese' => '太陽',
                'Serbian' => 'сунце',
                'is_active' => true,
                'category' => 'nature',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 9
            [
                'English' => 'moon',
                'Spanish' => 'luna',
                'French' => 'lune',
                'German' => 'Mond',
                'Japanese' => '月',
                'Serbian' => 'месец',
                'is_active' => true,
                'category' => 'nature',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 10
            [
                'English' => 'computer',
                'Spanish' => 'computadora',
                'French' => 'ordinateur',
                'German' => 'Computer',
                'Japanese' => 'コンピューター',
                'Serbian' => 'рачунар',
                'is_active' => true,
                'category' => 'technology',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 11
            [
                'English' => 'phone',
                'Spanish' => 'teléfono',
                'French' => 'téléphone',
                'German' => 'Telefon',
                'Japanese' => '電話',
                'Serbian' => 'телефон',
                'is_active' => true,
                'category' => 'technology',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 12
            [
                'English' => 'table',
                'Spanish' => 'mesa',
                'French' => 'table',
                'German' => 'Tisch',
                'Japanese' => 'テーブル',
                'Serbian' => 'сто',
                'is_active' => true,
                'category' => 'furniture',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 13
            [
                'English' => 'chair',
                'Spanish' => 'silla',
                'French' => 'chaise',
                'German' => 'Stuhl',
                'Japanese' => '椅子',
                'Serbian' => 'столица',
                'is_active' => true,
                'category' => 'furniture',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 14
            [
                'English' => 'pen',
                'Spanish' => 'bolígrafo',
                'French' => 'stylo',
                'German' => 'Stift',
                'Japanese' => 'ペン',
                'Serbian' => 'оловка',
                'is_active' => true,
                'category' => 'stationery',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 15
            [
                'English' => 'paper',
                'Spanish' => 'papel',
                'French' => 'papier',
                'German' => 'Papier',
                'Japanese' => '紙',
                'Serbian' => 'папир',
                'is_active' => true,
                'category' => 'stationery',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 16
            [
                'English' => 'tree',
                'Spanish' => 'árbol',
                'French' => 'arbre',
                'German' => 'Baum',
                'Japanese' => '木',
                'Serbian' => 'дрво',
                'is_active' => true,
                'category' => 'nature',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 17
            [
                'English' => 'flower',
                'Spanish' => 'flor',
                'French' => 'fleur',
                'German' => 'Blume',
                'Japanese' => '花',
                'Serbian' => 'цвет',
                'is_active' => true,
                'category' => 'nature',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 18
            [
                'English' => 'rain',
                'Spanish' => 'lluvia',
                'French' => 'pluie',
                'German' => 'Regen',
                'Japanese' => '雨',
                'Serbian' => 'киша',
                'is_active' => true,
                'category' => 'nature',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 19
            [
                'English' => 'snow',
                'Spanish' => 'nieve',
                'French' => 'neige',
                'German' => 'Schnee',
                'Japanese' => '雪',
                'Serbian' => 'снег',
                'is_active' => true,
                'category' => 'nature',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 20
            [
                'English' => 'river',
                'Spanish' => 'río',
                'French' => 'rivière',
                'German' => 'Fluss',
                'Japanese' => '川',
                'Serbian' => 'река',
                'is_active' => true,
                'category' => 'nature',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 21
            [
                'English' => 'mountain',
                'Spanish' => 'montaña',
                'French' => 'montagne',
                'German' => 'Berg',
                'Japanese' => '山',
                'Serbian' => 'планина',
                'is_active' => true,
                'category' => 'nature',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 22
            [
                'English' => 'coffee',
                'Spanish' => 'café',
                'French' => 'café',
                'German' => 'Kaffee',
                'Japanese' => 'コーヒー',
                'Serbian' => 'кафа',
                'is_active' => true,
                'category' => 'drink',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 23
            [
                'English' => 'tea',
                'Spanish' => 'té',
                'French' => 'thé',
                'German' => 'Tee',
                'Japanese' => 'お茶',
                'Serbian' => 'чај',
                'is_active' => true,
                'category' => 'drink',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 24
            [
                'English' => 'milk',
                'Spanish' => 'leche',
                'French' => 'lait',
                'German' => 'Milch',
                'Japanese' => '牛乳',
                'Serbian' => 'млеко',
                'is_active' => true,
                'category' => 'drink',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 25
            [
                'English' => 'bread',
                'Spanish' => 'pan',
                'French' => 'pain',
                'German' => 'Brot',
                'Japanese' => 'パン',
                'Serbian' => 'хлеб',
                'is_active' => true,
                'category' => 'food',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 26
            [
                'English' => 'cheese',
                'Spanish' => 'queso',
                'French' => 'fromage',
                'German' => 'Käse',
                'Japanese' => 'チーズ',
                'Serbian' => 'сир',
                'is_active' => true,
                'category' => 'food',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 27
            [
                'English' => 'butter',
                'Spanish' => 'mantequilla',
                'French' => 'beurre',
                'German' => 'Butter',
                'Japanese' => 'バター',
                'Serbian' => 'путер',
                'is_active' => true,
                'category' => 'food',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 28
            [
                'English' => 'egg',
                'Spanish' => 'huevo',
                'French' => 'œuf',
                'German' => 'Ei',
                'Japanese' => '卵',
                'Serbian' => 'јаје',
                'is_active' => true,
                'category' => 'food',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 29
            [
                'English' => 'fish',
                'Spanish' => 'pescado',
                'French' => 'poisson',
                'German' => 'Fisch',
                'Japanese' => '魚',
                'Serbian' => 'риба',
                'is_active' => true,
                'category' => 'food',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 30
            [
                'English' => 'chicken',
                'Spanish' => 'pollo',
                'French' => 'poulet',
                'German' => 'Huhn',
                'Japanese' => '鶏肉',
                'Serbian' => 'пилетина',
                'is_active' => true,
                'category' => 'food',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }

}
